---
- hosts: all
  become: yes
  tasks:
    - name: Install Java
      package:
        name:
        - java
        - tar
        state: present
    - name: add group "tomcat"
      group: name=tomcat
    - name: add user "tomcat"
      user: name=tomcat group=tomcat createhome=yes
    - name: Download Tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.14/bin/apache-tomcat-10.0.14.tar.gz
        dest: /opt/apache-tomcat-10.0.14.tar.gz
    - name: Extract Tomcat archive
      unarchive:
        remote_src: yes
        src: /opt/apache-tomcat-10.0.14.tar.gz
        dest: /opt/
    - name: Change ownership of Tomcat installation
      file: path=/opt/apache-tomcat-10.0.14 owner=tomcat group=tomcat state=directory recurse=yes
    - name: Start Tomcat
      command: nohup /opt/apache-tomcat-10.0.14/bin/startup.sh
      become: true
    - name: permit traffic in default zone for port 8080
      firewalld:
        port: 8080/tcp
        permanent: yes
        state: enabled
    - name: wait for tomcat to start
      wait_for: port=8080